#!/bin/bash

# This script is now OPTIONAL - the Python generator already creates category files automatically.
# Use this only if you want to create custom category combinations beyond what's in the JSON.

# Directory containing individual service files
SERVICE_DIR="services/lists"

# Directory to output combined category files
OUTPUT_DIR="services/categories"
mkdir -p "$OUTPUT_DIR"

echo "=========================================="
echo "CUSTOM CATEGORY BUILDER"
echo "=========================================="
echo "Note: Standard categories are auto-generated by generate_blocklists_fixed.py"
echo "This script creates additional custom category combinations."
echo ""

# Define CUSTOM categories that combine multiple auto-generated categories
# These are in addition to the auto-generated ones from the JSON files

declare -A custom_categories

# Example: Combine all entertainment (social + streaming + gaming + music)
custom_categories["entertainment"]="social dating gaming streaming adult music"

# Example: All distraction sources
custom_categories["productivity_blocklist"]="social dating gaming streaming adult"

# Example: Family-safe (everything except adult)
custom_categories["family_safe"]="social dating gaming streaming phishing malware"

# Loop through custom categories
for custom_cat in "${!custom_categories[@]}"; do
    echo "Building custom category: $custom_cat..."
    output_file="$OUTPUT_DIR/${custom_cat}.txt"
    : > "$output_file"  # Clear the output file
    
    # Get the source categories to combine
    source_cats=${custom_categories[$custom_cat]}
    
    # Loop over each source category file
    for source_cat in $source_cats; do
        source_file="$OUTPUT_DIR/${source_cat}.txt"
        
        if [[ -f "$source_file" ]]; then
            # Append contents (already plain domains from Python script)
            cat "$source_file" >> "$output_file"
            echo "  ✓ Added $source_cat"
        else
            echo "  ⚠️  Missing category file: $source_file"
        fi
    done
    
    # Deduplicate and sort
    if [[ -f "$output_file" ]]; then
        sort -u "$output_file" -o "$output_file"
        domain_count=$(wc -l < "$output_file")
        echo "  ✅ $custom_cat: $domain_count unique domains"
    fi
done

echo ""
echo "=========================================="
echo "Custom categories built successfully!"
echo "=========================================="
echo ""
echo "Available category files in $OUTPUT_DIR:"
ls -lh "$OUTPUT_DIR"/*.txt | awk '{print "  " $9 " (" $5 ")"}'
